add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 5
home_symbol = "home"
format = "[$path](bold blue)[$lock_symbol]($lock_style) "

[time]
time_format = "%H:%M"
format = "$time($style) "
style = "bright-white"
disabled = false

[cmd_duration]
min_time = 20_000  # Show command duration over 10,000 milliseconds (=20 sec)
format = " took [$duration]($style)"
